version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-west-2:860061945305:task-definition/audit-checklist-task-1:1"
        LoadBalancerInfo:
          ContainerName: "dh-javafse-audit-checklist-service"
          ContainerPort: "8200"
        PlatformVersion: "LATEST"